### ISSUE TITLE
_endRow default value is "1000"

### ISSUE THREAD

**Issue by moniprecup** [arodiss/XlsBundle#27]
I need to add validation for values from an excel file, but I get errors for some of the rows because the iterator goes until row 1000 even if in my excel file I have only 15 lines of data. 
Is there a way to check if the row is populated? Or to get last row with data? 

![image](https://user-images.githubusercontent.com/7113361/30645643-ff40fbaa-9e1e-11e7-87b7-16013f3de064.png)

**Comment by arodiss** [comment]
I can't say what your exact problem is, but:

- PHPExcel (library wrapped by this bundle) is often buggy and this is barely fixable
- If cell has no data, but has some formatting - it is considered to be "real" cell by PHPExcel, i.e. is included in iterator
- You can use `PythonReader` instead of default `PHPOfficeReader` - it does not have beforementioned problem with empty formatted cells. Though it has no real iterator - all data is loaded in memory in one piece, so don't use it for really big files
